runtime: go116
instance_class: F1
app_engine_apis: true

automatic_scaling:
  min_pending_latency: 50ms
  max_pending_latency: 500ms
  max_instances: 1

handlers:
- url: /.*
  script: auto
  secure: always
